import { NextResponse } from 'next/server';

const ASIAN_COUNTRIES = [
  { name: { common: "China" }, population: 1412600000, capital: ["Beijing"], region: "Asia" },
  { name: { common: "India" }, population: 1380004385, capital: ["New Delhi"], region: "Asia" },
  { name: { common: "Indonesia" }, population: 273523615, capital: ["Jakarta"], region: "Asia" },
  { name: { common: "Pakistan" }, population: 220892340, capital: ["Islamabad"], region: "Asia" },
  { name: { common: "Bangladesh" }, population: 164689383, capital: ["Dhaka"], region: "Asia" },
  { name: { common: "Japan" }, population: 125836021, capital: ["Tokyo"], region: "Asia" },
  { name: { common: "Philippines" }, population: 109581078, capital: ["Manila"], region: "Asia" },
  { name: { common: "Vietnam" }, population: 97338579, capital: ["Hanoi"], region: "Asia" },
  { name: { common: "Turkey" }, population: 83429615, capital: ["Ankara"], region: "Asia" },
  { name: { common: "Iran" }, population: 83992949, capital: ["Tehran"], region: "Asia" },
  { name: { common: "Thailand" }, population: 69799978, capital: ["Bangkok"], region: "Asia" },
  { name: { common: "Myanmar" }, population: 54409800, capital: ["Naypyidaw"], region: "Asia" },
  { name: { common: "South Korea" }, population: 51780579, capital: ["Seoul"], region: "Asia" },
  { name: { common: "Iraq" }, population: 40222493, capital: ["Baghdad"], region: "Asia" },
  { name: { common: "Afghanistan" }, population: 38928346, capital: ["Kabul"], region: "Asia" },
  { name: { common: "Saudi Arabia" }, population: 34813871, capital: ["Riyadh"], region: "Asia" },
  { name: { common: "Uzbekistan" }, population: 33469203, capital: ["Tashkent"], region: "Asia" },
  { name: { common: "Malaysia" }, population: 32365999, capital: ["Kuala Lumpur"], region: "Asia" },
  { name: { common: "Yemen" }, population: 29825968, capital: ["Sana'a"], region: "Asia" },
  { name: { common: "Nepal" }, population: 29136808, capital: ["Kathmandu"], region: "Asia" },
  { name: { common: "North Korea" }, population: 25778816, capital: ["Pyongyang"], region: "Asia" },
  { name: { common: "Sri Lanka" }, population: 21919000, capital: ["Sri Jayawardenepura Kotte"], region: "Asia" },
  { name: { common: "Kazakhstan" }, population: 18776707, capital: ["Nur-Sultan"], region: "Asia" },
  { name: { common: "Syria" }, population: 17500658, capital: ["Damascus"], region: "Asia" },
  { name: { common: "Cambodia" }, population: 16718965, capital: ["Phnom Penh"], region: "Asia" },
  { name: { common: "Jordan" }, population: 10203140, capital: ["Amman"], region: "Asia" },
  { name: { common: "Azerbaijan" }, population: 10139177, capital: ["Baku"], region: "Asia" },
  { name: { common: "United Arab Emirates" }, population: 9890402, capital: ["Abu Dhabi"], region: "Asia" },
  { name: { common: "Tajikistan" }, population: 9537645, capital: ["Dushanbe"], region: "Asia" },
  { name: { common: "Israel" }, population: 9216900, capital: ["Jerusalem"], region: "Asia" },
  { name: { common: "Laos" }, population: 7275560, capital: ["Vientiane"], region: "Asia" },
  { name: { common: "Lebanon" }, population: 6825445, capital: ["Beirut"], region: "Asia" },
  { name: { common: "Kyrgyzstan" }, population: 6591600, capital: ["Bishkek"], region: "Asia" },
  { name: { common: "Turkmenistan" }, population: 6031200, capital: ["Ashgabat"], region: "Asia" },
  { name: { common: "Singapore" }, population: 5850342, capital: ["Singapore"], region: "Asia" },
  { name: { common: "Oman" }, population: 4520471, capital: ["Muscat"], region: "Asia" },
  { name: { common: "Palestine" }, population: 4803269, capital: ["Ramallah"], region: "Asia" },
  { name: { common: "Kuwait" }, population: 4270571, capital: ["Kuwait City"], region: "Asia" },
  { name: { common: "Georgia" }, population: 3989167, capital: ["Tbilisi"], region: "Asia" },
  { name: { common: "Mongolia" }, population: 3278292, capital: ["Ulaanbaatar"], region: "Asia" },
  { name: { common: "Armenia" }, population: 2963243, capital: ["Yerevan"], region: "Asia" },
  { name: { common: "Qatar" }, population: 2881053, capital: ["Doha"], region: "Asia" },
  { name: { common: "Bahrain" }, population: 1701575, capital: ["Manama"], region: "Asia" },
  { name: { common: "Timor-Leste" }, population: 1318445, capital: ["Dili"], region: "Asia" },
  { name: { common: "Cyprus" }, population: 1207359, capital: ["Nicosia"], region: "Asia" },
  { name: { common: "Bhutan" }, population: 771608, capital: ["Thimphu"], region: "Asia" },
  { name: { common: "Maldives" }, population: 540544, capital: ["Malé"], region: "Asia" },
  { name: { common: "Brunei" }, population: 437479, capital: ["Bandar Seri Begawan"], region: "Asia" },
];

export async function GET() {
  return NextResponse.json(ASIAN_COUNTRIES);
}
